title: "Guardian Link"
description: "Security automation for Discord with cross-server alerts, moderation intelligence, and audit-ready logs."
show_downloads: false
theme_color: "#1F1A7A"
footer_brand: "Afterparty Bot Labs"
footer_link: "https://afterpartylabs.xyz"
icon: "/assets/css/img/logo.png"
favicon: "/assets/css/img/favicon.png"
cta_invite_url: "https://discord.com/oauth2/authorize?client_id=1395491639459582113&scope=bot%20applications.commands&permissions=1375194967238"
topgg_url: "https://top.gg/bot/1395491639459582113/vote"
cta_support_url: "https://discord.com/invite/BusuZp2G8w"
cta_website_url: "https://afterpartylabs.xyz/bot/guardian-link"
url: "https://botlabs-xyz.github.io"
baseurl: "/guardian-link-docs"
markdown: kramdown
